<template><div><h1 id="_2-git变基合并" tabindex="-1"><a class="header-anchor" href="#_2-git变基合并"><span>2. Git变基合并</span></a></h1>
<h2 id="_1-rebase分支合并" tabindex="-1"><a class="header-anchor" href="#_1-rebase分支合并"><span>1 rebase分支合并</span></a></h2>
<h3 id="_1-1-说明" tabindex="-1"><a class="header-anchor" href="#_1-1-说明"><span>1.1 说明</span></a></h3>
<p>以下 <code v-pre>v2</code> 是某个需求的开发分支， <code v-pre>dev</code>是总的开发分支，<code v-pre>v2</code> 是基于<code v-pre>dev</code>分支签出的。</p>
<p>当完成<code v-pre>v2</code>的开发后，需要把代码合并到<code v-pre>dev</code>，我们可以使用<code v-pre>rebase</code>进行合并：</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 首先将 v2 push到远程仓库</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> add</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> commit</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'xxx'</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 切换到 dev 拉取最新代码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 切换到 v2</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 将 v2 的所有[commit] 变基到(应用到) dev</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 切换到 dev</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> merge</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">  # 将 dev分支 快进合并 （此时 (HEAD -> dev, v2) [commit] 两个分支指向同一个提交）</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查看 原v2的[commit]记录 是否在dev分支的最前面（变基成功会把v2的提交记录应用到dev分支的最前面）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> log</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 如果到这一步发现有问题，尝试使用 git --abort中止变基，如果还是有问题的可以在dev分支上使用《后悔药》操作， 再到v2分支上使用《后悔药》操作，即可使两个分支都回退到 rebase变基 之前的状态</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 试运行项目是否有问题</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">yarn</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> start</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> status</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 查看状态是否有问题</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 推送到远程仓库的 dev</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-2-变基要遵守的准则" tabindex="-1"><a class="header-anchor" href="#_1-2-变基要遵守的准则"><span>1.2 变基要遵守的准则</span></a></h3>
<p><strong>几个人同时在一个分支上进行开发和提交时，开发中途请不要私自执行变基，只有在大家都完成工作之后才可以执行变基。</strong></p>
<h3 id="_1-3-变基的实质" tabindex="-1"><a class="header-anchor" href="#_1-3-变基的实质"><span>1.3 变基的实质</span></a></h3>
<p>变基操作的实质是丢弃一些现有的提交，然后相应地新建一些内容一样但实际上不同的提交。<br>
因此，<strong>变基操作过后的分支将不要再使用</strong>。</p>
<h2 id="_2-后悔药" tabindex="-1"><a class="header-anchor" href="#_2-后悔药"><span>2 后悔药</span></a></h2>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查看HEAD指针变动记录</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reflog</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 记录示例(当前分支是v2):</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> moving</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">1}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (finish): returning to refs/heads/master</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (start): checkout v2</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">15a97d8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD@{</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reset:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> moving</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 15a97d8</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> merge</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Fast-forward</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">15a97d8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD@{</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> moving</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">6}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (finish): returning to refs/heads/v2</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07c398f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (HEAD -> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">v2,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) HEAD@{</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">7}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (pick): C</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">15a97d8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD@{</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (start): checkout master </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 首次rebase</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d278ecd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD@{</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> checkout:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> moving</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # rebase前的状态</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">15a97d8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD@{</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> commit:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> D</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 可见，示例中最初的 rebase 操作是 HEAD@{8}，想回退到变基前的状态需让指针指向 HEAD@{9}</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reset</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --hard</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> d278ecd</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">  # 重置当前分支的HEAD为指定[commit]，同时重置暂存区和工作区，与指定[commit]一致</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 此时打印 log 查看是否回到之前的状态</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> log</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>注意：此操作只能回退当前的分支，如其他分支也要回退，需要切换到该分支并执行上面操作。</strong></p>
<h2 id="_3-开发期间的rebase操作" tabindex="-1"><a class="header-anchor" href="#_3-开发期间的rebase操作"><span>3 开发期间的rebase操作</span></a></h2>
<h3 id="_3-1-背景" tabindex="-1"><a class="header-anchor" href="#_3-1-背景"><span>3.1 背景</span></a></h3>
<p>有两个分支：</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dev</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">*v2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>v2</code> 是基于<code v-pre>dev</code>切出来的。</p>
<p>提交记录如下：</p>
<div class="language-git line-numbers-mode" data-highlighter="shiki" data-ext="git" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-git"><span class="line"><span>  dev</span></span>
<span class="line"><span>a - b - c</span></span>
<span class="line"><span>  v2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>开发期间，两个分支同时有新的commit ：</p>
<div class="language-git line-numbers-mode" data-highlighter="shiki" data-ext="git" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-git"><span class="line"><span>  dev</span></span>
<span class="line"><span>a - b - c - d - e</span></span>
<span class="line"><span>    \ - f - g</span></span>
<span class="line"><span>      v2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当前你正在<code v-pre>v2</code>进行开发，<code v-pre>dev</code>也同时进行开发，并有重大的改变，你需要把<code v-pre>dev</code>的提交同步到<code v-pre>v2</code>。</p>
<p><strong>需求： 把<code v-pre>dev</code>中新的提交同步到<code v-pre>v2</code>，且不能影响<code v-pre>dev</code>分支。</strong></p>
<h3 id="_3-2-操作步骤" tabindex="-1"><a class="header-anchor" href="#_3-2-操作步骤"><span>3.2 操作步骤</span></a></h3>
<ol>
<li>
<p>基于最新的 <code v-pre>dev</code> 切一个新的分支 <code v-pre>dev-copy</code></p>
<blockquote>
<p><code v-pre>dev-copy</code> 和 <code v-pre>dev</code>  两者的 commit ID 一致。</p>
</blockquote>
</li>
<li>
<p>在<code v-pre>dev-copy</code>中执行rebase，将 <code v-pre>dev-copy</code> 的提交变基到 <code v-pre>v2</code></p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rebase</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 将 dev-copy 的提交[commit] 变基到(应用到) v2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>删除原<code v-pre>v2</code>分支，将<code v-pre>dev-copy</code>分支名改为<code v-pre>v2</code></p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 当前在 dev-copy 分支</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> branch</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -d</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 删除分支</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> branch</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dev-copy</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v2</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # 重命名</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ol>
<h2 id="_3-git-cherry-pick" tabindex="-1"><a class="header-anchor" href="#_3-git-cherry-pick"><span>3 git cherry-pick</span></a></h2>
<p>来源：<a href="http://www.ruanyifeng.com/blog/2020/04/git-cherry-pick.html" target="_blank" rel="noopener noreferrer">《git cherry-pick 教程》</a></p>
<p>用于将单个或几个<code v-pre>[commit]</code>复制到另一个分支。</p>
<h3 id="_3-1-基本应用" tabindex="-1"><a class="header-anchor" href="#_3-1-基本应用"><span>3.1 基本应用</span></a></h3>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> cherry-pick</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">commitHas</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">h> </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 将commitHash应用于当前分支</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上面命令就会将指定的提交<code v-pre>commitHash</code>，应用于当前分支。这会在当前分支产生一个新的提交，当然它们的<strong>哈希值会不一样</strong>。</p>
<p>git cherry-pick命令的参数，不一定是提交的哈希值，分支名也是可以的，表示转移该分支的最新提交。</p>
<h3 id="_3-2-转移多个提交" tabindex="-1"><a class="header-anchor" href="#_3-2-转移多个提交"><span>3.2 转移多个提交</span></a></h3>
<p>Cherry pick 支持一次转移多个提交。</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> cherry-pick</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Hash</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">A> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Hash</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">B> </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># A和B提交</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上面的命令将 A 和 B 两个提交应用到当前分支。这会在当前分支生成两个对应的新提交。</p>
<p>如果想要转移一系列的连续提交，可以使用下面的简便语法。</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> cherry-pick</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> A..B</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # A到B提交，不包含A</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上面的命令可以转移从 A 到 B 的所有提交。它们必须按照正确的顺序放置：提交 A 必须早于提交 B，否则命令将失败，但不会报错。</p>
<p><strong>注意，使用上面的命令，提交 A 将不会包含在 Cherry pick 中。如果要包含提交 A，可以使用下面的语法。</strong></p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> cherry-pick</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> A^..B</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # A到B提交，包含A</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


