import comp from "E:/R-blog/src/.vuepress/.temp/pages/Tools/MarkDown/markdown01.html.vue"
const data = JSON.parse("{\"path\":\"/Tools/MarkDown/markdown01.html\",\"title\":\"Markdown方言（Vuepress）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":1,\"date\":\"2023-04-08T00:00:00.000Z\",\"cover\":\"https://simeis147-github-io.oss-cn-shenzhen.aliyuncs.com/BackEnd/SpringCloud/20230627144902.png\",\"category\":[\"Markdown\"],\"description\":\"Markdown方言（Vuepress） 1 提示信息 info note tip warning danger details 2 Emoji表情 效果： 😉 😢 😆 😋 😎 😃 😗 😦 😃 😦 😉 3 字体颜色 3.1 配置重要 class=\\\"vp-badge info\\\" class=\\\"vp-badge danger\\\" cla...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Markdown方言（Vuepress）\\\",\\\"image\\\":[\\\"https://simeis147-github-io.oss-cn-shenzhen.aliyuncs.com/BackEnd/SpringCloud/20230719202045.png\\\",\\\"https://simeis147-github-io.oss-cn-shenzhen.aliyuncs.com/BackEnd/SpringCloud/20230719202130.png\\\"],\\\"datePublished\\\":\\\"2023-04-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.R\\\",\\\"url\\\":\\\"https://github.com/WillebrordSnell\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/Tools/MarkDown/markdown01.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\" \"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Markdown方言（Vuepress）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Markdown方言（Vuepress） 1 提示信息 info note tip warning danger details 2 Emoji表情 效果： 😉 😢 😆 😋 😎 😃 😗 😦 😃 😦 😉 3 字体颜色 3.1 配置重要 class=\\\"vp-badge info\\\" class=\\\"vp-badge danger\\\" cla...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://simeis147-github-io.oss-cn-shenzhen.aliyuncs.com/BackEnd/SpringCloud/20230627144902.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://simeis147-github-io.oss-cn-shenzhen.aliyuncs.com/BackEnd/SpringCloud/20230627144902.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Markdown方言（Vuepress）\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-04-08T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":1.16,\"words\":349},\"filePathRelative\":\"Tools/MarkDown/markdown01.md\",\"excerpt\":\"\\n<h2>1 提示信息</h2>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">info</p>\\n</div>\\n<div class=\\\"hint-container note\\\">\\n<p class=\\\"hint-container-title\\\">note</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">tip</p>\\n</div>\\n<div class=\\\"hint-container warning\\\">\\n<p class=\\\"hint-container-title\\\">warning</p>\\n</div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
