export const themeData = JSON.parse("{\"encrypt\":{},\"author\":{\"name\":\"Mr.R\",\"url\":\"https://github.com/WillebrordSnell\"},\"logo\":\"https://theme-hope-assets.vuejs.press/logo.svg\",\"repo\":\"\",\"docsDir\":\"src\",\"footer\":\"西湖美景, 三月天嘞~\",\"displayFooter\":true,\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"打印\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"星标\",\"empty\":\"$text 为空\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"routerLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\"},\"navbar\":[{\"text\":\"🔧 工具\",\"prefix\":\"/Tools/\",\"children\":[{\"text\":\"文档\",\"children\":[{\"text\":\"Markdown\",\"link\":\"MarkDown/\"},{\"text\":\"资源整合\",\"link\":\"Resource/\"}]},{\"text\":\"工具\",\"children\":[{\"text\":\"Git\",\"link\":\"Git/\"}]}]},{\"text\":\"  📑 码头\",\"prefix\":\"/keyan/\",\"children\":[{\"text\":\"视频理解\",\"link\":\"videoUnderstanding/_videoUnderstanding\"},{\"text\":\"视频表征\",\"link\":\"videoRepresentation/_videoRepresentation\"},{\"text\":\"视频对话\",\"link\":\"videoDialog/_videoDialog\"},{\"text\":\"对比学习\",\"link\":\"contrastiveLearning/_contrastiveLearning\"},{\"text\":\"经典对抗攻击\",\"link\":\"adversarialExample/adversarial-example\"},{\"text\":\"无限制对抗攻击\",\"link\":\"unrestrictedAdversarialExamples/unrestricted-adversarial-examples\"}]},{\"text\":\"  🧫 炉\",\"prefix\":\"/train/\",\"children\":[{\"text\":\"单机多卡DDP\",\"link\":\"DDP/_DDP\"},{\"text\":\"AVSD\",\"link\":\"AVSD/_AVSD\"},{\"text\":\"奇淫技巧\",\"link\":\"trick/_trick\"}]}],\"sidebar\":{\"/keyan/\":[\"videoUnderstanding/videoUnderstanding\",\"videoRepresentation/videoRepresentation\",\"videoDialog/videoDialog\",\"contrastiveLearning/contrastiveLearning\",\"adversarialExample/adversarial-example\",\"unrestrictedAdversarialExamples/unrestricted-adversarial-examples\"],\"/book/\":[\"202309\",\"202310\",\"202311\",\"maoxuan\"],\"/train/\":[\"DDP/DDP\",\"AVSD/AVSD\",\"trick/trick\"],\"/Tools/Git/\":\"structure\",\"/Tools/Git/*\":\"structure\",\"/Tools/MarkDown/\":\"structure\",\"/Tools/Resource/\":\"structure\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
